// GENERATED by scripts/curate-media.mjs — do not edit by hand.
// Source files live in media/. Re-run `npm run media` after new uploads.

export type Photo = {
  /** Stem of the files in /photos: `${id}-${width}.webp`. */
  id: string;
  /** English alt text. Hindi alt text is keyed by id in content/copy/hi.ts. */
  alt: string;
  /** Intrinsic size of the largest rendition, for width/height attributes. */
  width: number;
  height: number;
  /** Widths actually emitted, largest first, for the srcset. */
  widths: number[];
  /** 24px WebP data URI, painted under the image while it loads. */
  blur: string;
};

export const photos = {
  "hero-raider": {
    "id": "hero-raider",
    "alt": "A red and black TVS Raider on the showroom floor at Shiv Kripa Motors, with more bikes lined up behind it.",
    "width": 1600,
    "height": 900,
    "widths": [
      1600,
      1200,
      800,
      480
    ],
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBACdASoYAA0APu1iqU2ppaOiMAgBMB2JbACdDiAAK+RszEVHwBXGczgA+gPN6gRp5OdOaAzaHP3TTE9udjlOJXcOb229Hs/UA9c/GOpjw1nt69NBpWqVRTc0t91IlCegC9ic4dAg+O1CqrDhpjcGnEZcEuAxdEcr9q2TOZdKYBqHT0UuPuduOBJreAU/FBGX+WlY5FKU8kL/wOWKXYSFqYmAAA=="
  },
  "hero-floor": {
    "id": "hero-floor",
    "alt": "A row of new TVS Raider and Apache motorcycles lined up along the showroom floor.",
    "width": 900,
    "height": 1600,
    "widths": [
      900,
      800,
      480
    ],
    "blur": "data:image/webp;base64,UklGRoYBAABXRUJQVlA4IHoBAADQBwCdASoYACsAPu1kqE8ppSOiKqwBMB2JbACdM2nUir9eS4tHB8JrLbj3dcMNJ0YCz0fWIK4JiaBqIpQ9XH2EscJ5BwibwAD+Xt8XSaUJ+KnCxjrSJoe5WadFfk4DZ4AYjATdpsOo6XV72UquNSjHnSPVZlUDzA7MAJ8dm4gTW8kb4bdg+K1zMCAUhVBgVYf5tnhVM2SVCnUoM7yuQXi5ZOq7yciJk+RLU0tU760kNiXXlwEIcihTjvCUMmx8Y+TuFAFTsQekOwP9yiY9MAon5TYRTGavzgeGI4kKRGkLvPukNkE+WvKWfcLNWQRwljFNUiqWdCGssQbt8btDYLLuaFtuu2x6zPAE3oG/TRqMcGQWn8rrYb1ZmWfDFwrtLI652yMAL42U30Qfc4uVFrEyHq2cuNdc/2ibTU7yJPRVavz/+JRtujgrHkEO17l4J/tjwahKkDsfTZFInJldv2FRUmkr7bd9ENPnEvk38JDeL2/6HJn8D0eAAAA="
  },
  "storefront": {
    "id": "storefront",
    "alt": "The Shiv Kripa Motors showroom front on Bilaspur Road, Kota, under the TVS dealer sign.",
    "width": 1280,
    "height": 720,
    "widths": [
      1280,
      1200,
      800,
      480
    ],
    "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JZwAAUlhyn0Q8XGgA/uf/KPW4O+Gz41jH0pI2vpoN9U4nZjBj7m2S53K6UyZXc83PWRG+Na30I+p1+IBNYXd30SMGf5iwQDqIYMZLI9s9EvqIt3LUS9pdkOvSa1KncT0D4woWnH/L8xyJbkI1RwYiRHeiLD8HgAA="
  },
  "opening-day": {
    "id": "opening-day",
    "alt": "The Shiv Kripa Motors team outside the showroom on opening day.",
    "width": 1080,
    "height": 723,
    "widths": [
      1080,
      800,
      480
    ],
    "blur": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYgC7AB8wvEhVdLxaLorfA0AA/uuCBMBLBgYqHIUfEB3ad3WCpasDY7YWs2OG1b1SmUpnzIKSk2RASvuZ+yH84BblJe4yFZCdvR0HY17Z7tH7Dh+y70d62PnIH9uLEkga+vrxXd9b/nRRsxVd0JzegJ7tB3MJlHMyQtYmZbq9+N7qXRaWgQkCEqHkXuVlO4AAAA=="
  },
  "opening-floor": {
    "id": "opening-floor",
    "alt": "The showroom on opening day, scooters and motorcycles ready on the floor behind the ribbon.",
    "width": 1280,
    "height": 853,
    "widths": [
      1280,
      1200,
      800,
      480
    ],
    "blur": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JQBOgBDfQpFO2ilhmV4z6GsCQAMtAz1QS469xk6ZMGxsg1v+wfTFqmrPUyGmL60wu9+ERz2C6OSzO94yMbpfQJ11QEAnEeS7JprttySSyLkVP96s0jGqzv+kg2Lafr6wVyoksF9gd/kXqx7oNXTh8Ab+GhsSy8NQAAA=="
  },
  "first-delivery": {
    "id": "first-delivery",
    "alt": "A new TVS Jupiter being handed over to its owner at the showroom.",
    "width": 1280,
    "height": 853,
    "widths": [
      1280,
      1200,
      800,
      480
    ],
    "blur": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAADwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JagCdMoBOAbU87RJ8d80pyV+LRAMH/4gA99RlpKBAzkwuR3EFVRnSUawcVD2ipcEYRJ29p1ugfRC3ygMNdk3ne8ZfDAQySS4Ntr9ADpWM1tIqCDpQ8PySZDoPHvQOmCzQeGjT1hz4fHeK0I3lvwkicXraysvntR4LJzUUbGNgLMTAOG1oJ9sN1aV5IRxv+69XUhO6H5bTCKhRq6brn9dIyFhmW0Ae8G3KFOCNfKAAAA=="
  },
  "scooters": {
    "id": "scooters",
    "alt": "Two TVS scooters parked side by side inside the showroom.",
    "width": 1280,
    "height": 720,
    "widths": [
      1280,
      1200,
      800,
      480
    ],
    "blur": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAABwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbAC2yYwmpgb8SEMY81oIYwVWAAD+mLYxrEryYIkQHzsyn87twKvMWFmuBnVNEm/gEWrE9JSop6xa2uY0/aBfun5mfLoP5aSw3OCMQGqsdSn0hFwGhNsAgPL16/30u9a0Zs9FXXmxfN6zOvW98lnAJvoip6h4J8JH/fSwi0sIcCtCj/yQm8v4gsgAAA=="
  }
} as const satisfies Record<string, Photo>;

export type PhotoId = keyof typeof photos;

/** `srcset` for a curated photo, in the order browsers expect. */
export function srcSet(id: PhotoId): string {
  return photos[id].widths.map((w) => `/photos/${id}-${w}.webp ${w}w`).join(', ');
}

/** Largest rendition, used as the `src` fallback. */
export function src(id: PhotoId): string {
  return `/photos/${id}-${photos[id].widths[0]}.webp`;
}

/** The showroom clip: desktop-only, muted, seven seconds, no audio track. */
export const showroomClip = {
  "src": "/video/showroom.mp4",
  "poster": "/photos/showroom-clip-1200.webp",
  "width": 1024,
  "height": 576,
  "blur": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAwBACdASoYAA4APu1iqU2ppaQiMAgBMB2JbACdMoADK6i0PzTlY9WNXQAArTm8T5dTeryckUNywW3yCQWJLcixWB80Xw7OiKFqk8uwczBK/IU5K+55Hj3nWhA0Ih0ajDxmEMz3xRwdcwqRuqkF3AmONe0W7ccUiSdJqcBxiRr+nDXH4yCWFl5NjEZiggO9flMO+OfzlQIAiF441GegAA=="
};
